### ISSUE TITLE
naming of this module/plugin of different lammps-engines

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps-md#19]
Currently, the **lammps-md** (FILE-IO) wrapper is a class called `LammpsWrapper` (in package is called `simlamps`) and it is integrated into the simphony-engine so that it looks like:

```
from simphony.engine import lammps

wrapper = lammps.LammpsWrapper()
```

This should be evaluated. Especially once we have other lammps-based engines supported (e.g. **lammps-sph**, **lammps-dem**....) and INTERNAL INTERFACE (not just FILE-IO)

**Comment by nathanfranklin** [comment]
```
from simphony.engine import lammps
    wrapper = lammps.LammpsWrapper()
```

should probably be something like 

```
from simphony.engine import lammps
    lammps_md_engine = lammps.LammpsMD()
```

**Comment by nathanfranklin** [comment]
@mehdisadeghi @ahashibon 

I think LammpsMD would be a good name intead of LammpsWrapper.  With LammpsDEM adn LammpsSPH being the future wrappers of lammp.

```
from simphony.engine import lammps
    lammps_md_engine = lammps.LammpsMD()
```

**Comment by ahashibon** [comment]
Agree, this is a good choice, allowing the end user enough freedom to choose, mix and match different wrappers in each application.

**Comment by nathanfranklin** [comment]
or maybe just MD and DEM are better?

```
from simphony.engine import lammps
    lammps_md_engine = lammps.MD()
    lammps_dem_engine = lammps.DEM()
```
instead of
```
from simphony.engine import lammps
    lammps_md_engine = lammps.LammpsMD()
    lammps_dem_engine = lammps.LammpsDEM()
```

**Comment by ahashibon** [comment]
yes, even more elegant!

**Comment by mehdisadeghi** [comment]
What do DM and DEM stand for? wouldn't it be more readable if we use the explicit terms instead of abbreviations? For example:

```
import lammps as lm

lammps_md_engine = lm.MblablaDblabla()
lammps_dem_engine = lm.DblablaEblablaMblabla()
```

**Comment by ahashibon** [comment]
MD: Molecular Dynamics
DEM: Discrete Elements Method
these are widely accepted, de-facto standard, abbreviations.

**Comment by nathanfranklin** [comment]
That sound good. So:  

```
from simphony.engine import lammps
    lammps_md_engine = lammps.MolecularDynamics()
    lammps_dem_engine = lammps.DiscreteElementMethod()
    lammps_sph_engine = lammps.SmoothParticleHydrodynamics()
```

**Comment by nathanfranklin** [comment]
@mehdisadeghi , @ahashibon , @TobiasRasp  based on our discussion today:

The respostiory will be renamed from `simphony-lammps` to `simphony-lammps-liggghts`
and the package will be renamed from  `simlamps` to `simphony_lammps_liggghts`.  

And the plugin will be named `lammps_ligghts`, and use of it will look like the following:

```
from simphony.engine import lammps_ligghts
    lammps_md_engine = lammps_ligghts.MolecularDynamics()
    lammps_dem_engine = lammps_ligghts.DiscreteElementMethod()
    lammps_sph_engine = lammps_ligghts.SmoothParticleHydrodynamics()
```

I think having this renamed should occur before the next release of SimPhoNy-framework (i.e. the one using simphony 0.2.0)

**Comment by mehdisadeghi** [comment]
With introduction of CUDS class, this is a minor issue now and is internal to the wrapper. User will simply define the name of the wrapper and SimPhoNy will instantiate it.

The implementation of the wrapper classes can be improved, however. I will close this issue. Feel free to re-open in case of necessity.
