### ISSUE TITLE
support delete_particle in INTERNAL wrapper

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps-md#68]

**Comment by ahashibon** [comment]
There is a delete atoms method in lammps, that may be useful (we will need to add support for it to the library interface of lammps though... ) 
http://lammps.sandia.gov/doc/delete_atoms.html

**Comment by nathanfranklin** [comment]
all commands can be sent to the library interface of lammps.  We will have to try it out with the ```group``` command as ```delete_atoms``` command doesn't allow us to pick a single atom to be delete. 

my current plan was to restart the simulation with the deleted atoms removed.

**Comment by nathanfranklin** [comment]
>  I wonder if we can use the delete atoms method in lammps? (we will need to add support for it to the library interface of lammps though... )
http://lammps.sandia.gov/doc/delete_atoms.html

This turned out to have some issues.  `delete_atoms` command needed to be used the `compress` flag set to yes.  This caused a problem as the remaining atoms were given ids that seemed were not given predictable new ids.  So while it would be possible to determine what the new ids were by checking the value of the coordinates, I opted not to take this approach as it seemed error prone plus would not work once bonds were supported.  So in 149b0a43fc500a0b486133e2953164f31c7876cc, whenever a deletion occurs, a copy of all the non-deleted atoms is made before deleting all the atoms from lammps.  Then these saved atoms are added back to lammps.

**Comment by nathanfranklin** [comment]
closed by #83
